{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T12:33:00.000+0000",
      "latitude": 51.38937895120526,
      "estimatedRestoration": "2021-12-29T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5366'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5366",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.38809,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.06214
            },
            {
              "py/object": "Point",
              "latitude": 51.39059,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.05547
            },
            {
              "py/object": "Point",
              "latitude": 51.38975,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.05007
            },
            {
              "py/object": "Point",
              "latitude": 51.38809,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.06214
            }
          ],
          "subCodes": [
            "RG7 3AR",
            "RG7 3AT",
            "RG7 3JG",
            "RG7 3JH"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG5366",
      "engineerOnSiteTime": "2021-12-29T13:15:00.000+0000",
      "name": "RG7 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG7 3AR",
        "RG7 3AT",
        "RG7 3JG",
        "RG7 3JH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.06214,
              51.38809
            ],
            [
              -1.05547,
              51.39059
            ],
            [
              -1.05007,
              51.38975
            ],
            [
              -1.06214,
              51.38809
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "bca38e8f-d991-4888-9e89-478cbdd834c2",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.0564455316676278,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T16:10:00.000+0000",
      "latitude": 51.66264647226641,
      "estimatedRestoration": "2021-12-29T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5512'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5512",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.66224,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.71817
            },
            {
              "py/object": "Point",
              "latitude": 51.66252,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.71669
            },
            {
              "py/object": "Point",
              "latitude": 51.66318,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.71604
            },
            {
              "py/object": "Point",
              "latitude": 51.66224,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.71817
            }
          ],
          "subCodes": [
            "HP15 6BP",
            "HP15 6BU",
            "HP15 6BX"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG5512",
      "engineerOnSiteTime": "2021-12-29T17:45:00.000+0000",
      "name": "HP15 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "HP15 6BP",
        "HP15 6BU",
        "HP15 6BX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.71817,
              51.66224
            ],
            [
              -0.71669,
              51.66252
            ],
            [
              -0.71604,
              51.66318
            ],
            [
              -0.71817,
              51.66224
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2021-12-29T17:30:00.000+0000",
      "UUID": "cf651f4f-8d70-45cc-b72f-302b38f48f59",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7169392341208001,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T14:38:00.000+0000",
      "latitude": 51.81557651526522,
      "estimatedRestoration": "2021-12-29T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5465'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5465",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.81545,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.28844
            }
          ],
          "name": "OX5 1HJ",
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG5465",
      "name": "OX5 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX5 1HJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.288532520037462,
          51.81557651526522
        ],
        "type": "Point"
      },
      "UUID": "7ff3832f-0989-4ef2-a8f5-e22089d9cc2e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.288532520037462,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T17:44:00.000+0000",
      "latitude": 51.231972423874375,
      "estimatedRestoration": "2021-12-29T20:50:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5578'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5578",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.23125,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.80615
            },
            {
              "py/object": "Point",
              "latitude": 51.23192,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.80562
            },
            {
              "py/object": "Point",
              "latitude": 51.23331,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.8039
            },
            {
              "py/object": "Point",
              "latitude": 51.23335,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.80339
            },
            {
              "py/object": "Point",
              "latitude": 51.23113,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.80259
            },
            {
              "py/object": "Point",
              "latitude": 51.23091,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.80465
            },
            {
              "py/object": "Point",
              "latitude": 51.23125,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.80615
            }
          ],
          "subCodes": [
            "GU9 0DB",
            "GU9 0DE",
            "GU9 0DJ",
            "GU9 0DT",
            "GU9 0HU",
            "GU9 0HX"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG5578",
      "name": "GU9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU9 0DB",
        "GU9 0DE",
        "GU9 0DJ",
        "GU9 0DT",
        "GU9 0HU",
        "GU9 0HX"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.80615,
              51.23125
            ],
            [
              -0.80562,
              51.23192
            ],
            [
              -0.8039,
              51.23331
            ],
            [
              -0.80339,
              51.23335
            ],
            [
              -0.80259,
              51.23113
            ],
            [
              -0.80465,
              51.23091
            ],
            [
              -0.80615,
              51.23125
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "1b1ad399-a075-44e6-a5a9-f6d835baadb9",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8044060126912788,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T14:53:00.000+0000",
      "latitude": 51.42795813530183,
      "estimatedRestoration": "2021-12-30T02:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5471'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5471",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.42831,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.48304
            },
            {
              "py/object": "Point",
              "latitude": 51.42795813530183,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.4828421857469537
            },
            {
              "py/object": "Point",
              "latitude": 51.4276,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.48262
            },
            {
              "py/object": "Point",
              "latitude": 51.42831,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.48304
            }
          ],
          "subCodes": [
            "TW15 3NE",
            "TW15 3NF"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG5471",
      "engineerOnSiteTime": "2021-12-29T15:45:00.000+0000",
      "name": "TW15 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "TW15 3NE",
        "TW15 3NF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.48304,
              51.42831
            ],
            [
              -0.4828421857469537,
              51.42795813530183
            ],
            [
              -0.48262,
              51.4276
            ],
            [
              -0.48304,
              51.42831
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "66cabbbc-528f-4c4c-bd48-a083b893633c",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.4828421857469537,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T17:29:00.000+0000",
      "latitude": 51.37789636098181,
      "estimatedRestoration": "2021-12-30T05:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5572'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5572",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.37746,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.86905
            },
            {
              "py/object": "Point",
              "latitude": 51.3788,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.86719
            },
            {
              "py/object": "Point",
              "latitude": 51.37814,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.86648
            },
            {
              "py/object": "Point",
              "latitude": 51.37719,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.86775
            },
            {
              "py/object": "Point",
              "latitude": 51.37746,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.86905
            }
          ],
          "subCodes": [
            "RG40 4XB",
            "RG40 4XE",
            "RG40 4XF",
            "RG40 4XG"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG5572",
      "engineerOnSiteTime": "2021-12-29T18:05:00.000+0000",
      "name": "RG40 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG40 4XB",
        "RG40 4XE",
        "RG40 4XF",
        "RG40 4XG"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.86905,
              51.37746
            ],
            [
              -0.86719,
              51.3788
            ],
            [
              -0.86648,
              51.37814
            ],
            [
              -0.86775,
              51.37719
            ],
            [
              -0.86905,
              51.37746
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "b74ab87f-14be-4bfc-8b71-e8caeaeed7b5",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8676376550617648,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T16:40:00.000+0000",
      "latitude": 50.86152693850267,
      "estimatedRestoration": "2021-12-30T03:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5535'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5535",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.8627,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.15803
            },
            {
              "py/object": "Point",
              "latitude": 50.86132,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.15617
            },
            {
              "py/object": "Point",
              "latitude": 50.86018,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.15431
            },
            {
              "py/object": "Point",
              "latitude": 50.86201,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.15389
            },
            {
              "py/object": "Point",
              "latitude": 50.8627,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.15803
            }
          ],
          "subCodes": [
            "DT11 7HU",
            "DT11 7JN",
            "DT11 7LB",
            "DT11 7LD",
            "DT11 7LE",
            "DT11 7NJ",
            "DT11 7NL",
            "DT11 7NN",
            "DT11 7NZ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG5535",
      "name": "DT11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT11 7HU",
        "DT11 7JN",
        "DT11 7LB",
        "DT11 7LD",
        "DT11 7LE",
        "DT11 7NJ",
        "DT11 7NL",
        "DT11 7NN",
        "DT11 7NZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -2.15803,
              50.8627
            ],
            [
              -2.15617,
              50.86132
            ],
            [
              -2.15431,
              50.86018
            ],
            [
              -2.15389,
              50.86201
            ],
            [
              -2.15803,
              50.8627
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2021-12-29T20:00:00.000+0000",
      "UUID": "e57f8a94-3171-408a-b0af-ea14c68a4622",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1553189291864383,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T11:54:00.000+0000",
      "latitude": 55.467301633020384,
      "estimatedRestoration": "2021-12-29T21:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5336'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5336",
      "reference": "JG5336",
      "name": "PA28 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PA28",
        "PA28 6QP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -5.54761836580912,
          55.467301633020384
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2021-12-29T13:00:00.000+0000",
      "UUID": "c723c033-6332-476a-b0c4-c89cd916c841",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.54761836580912,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T14:05:00.000+0000",
      "latitude": 56.25118065096444,
      "estimatedRestoration": "2021-12-29T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5507'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5507",
      "reference": "JG5507",
      "name": "PA32 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PA32 8XD",
        "PA32 8XJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -5.081760011204957,
          56.25118065096444
        ],
        "type": "Point"
      },
      "UUID": "ffbc2bfa-05c1-4cc0-ac53-fd346decb3a2",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -5.081760011204957,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T16:51:00.000+0000",
      "latitude": 56.43856575253278,
      "estimatedRestoration": "2021-12-29T22:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5546'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5546",
      "reference": "JG5546",
      "name": "PH1 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PH1 3RY",
        "PH1 3SE",
        "PH1 3SN"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.6808123765616805,
          56.43856575253278
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2021-12-29T17:45:00.000+0000",
      "UUID": "92be1bda-0609-45d2-83eb-16a3dca55529",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.6808123765616805,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-29T17:42:00.000+0000",
      "latitude": 56.46899812807458,
      "estimatedRestoration": "2021-12-29T21:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG5530'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG5530",
      "reference": "JG5530",
      "engineerOnSiteTime": "2021-12-29T19:00:00.000+0000",
      "name": "DD2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD2 2DW",
        "DD2 2EY",
        "DD2 2EZ",
        "DD2 2HD",
        "DD2 2HE",
        "DD2 2HF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.0202027143844496,
          56.46899812807458
        ],
        "type": "Point"
      },
      "UUID": "e1655a0f-afe7-4bc7-82a1-7e3655c35ca6",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.0202027143844496,
      "resolved": false
    }
  ]
}
