{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T16:00:00.000+0000",
      "latitude": 50.98089514905781,
      "estimatedRestoration": "2021-12-17T19:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '204768'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/204768",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.97749,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.54439
            },
            {
              "py/object": "Point",
              "latitude": 50.98089514905781,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.5367745822064893
            },
            {
              "py/object": "Point",
              "latitude": 50.983,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.5322
            },
            {
              "py/object": "Point",
              "latitude": 50.98155,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.53181
            },
            {
              "py/object": "Point",
              "latitude": 50.97749,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.54439
            }
          ],
          "subCodes": [
            "SO51 6BB",
            "SO51 6BD",
            "SO51 6FZ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "204768",
      "name": "SO51 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO51 6BB",
        "SO51 6BD",
        "SO51 6FZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.54439,
              50.97749
            ],
            [
              -1.5367745822064893,
              50.98089514905781
            ],
            [
              -1.5322,
              50.983
            ],
            [
              -1.53181,
              50.98155
            ],
            [
              -1.54439,
              50.97749
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "91da7726-5f0a-4e86-884b-4b4a7e06c2ba",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.5367745822064893,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T16:24:00.000+0000",
      "latitude": 51.539313140726684,
      "estimatedRestoration": "2021-12-18T04:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JF9667'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JF9667",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.53993,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.9053
            },
            {
              "py/object": "Point",
              "latitude": 51.539313140726684,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.9045730579127018
            },
            {
              "py/object": "Point",
              "latitude": 51.53866,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.90387
            }
          ],
          "subCodes": [
            "SN4 7BU",
            "SN4 7DU"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JF9667",
      "engineerOnSiteTime": "2021-12-17T17:20:00.000+0000",
      "name": "SN4 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SN4 7BU",
        "SN4 7DU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.9053,
              51.53993
            ],
            [
              -1.9045730579127018,
              51.539313140726684
            ],
            [
              -1.90387,
              51.53866
            ],
            [
              -1.9053,
              51.53993
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2021-12-17T17:00:00.000+0000",
      "UUID": "91ef3844-bc56-4df9-9667-4e09dfce786d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.9045730579127018,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T14:55:00.000+0000",
      "latitude": 51.30306633027009,
      "estimatedRestoration": "2021-12-18T01:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JF9607'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JF9607",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.30296,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.21424
            },
            {
              "py/object": "Point",
              "latitude": 51.30314,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.21332
            },
            {
              "py/object": "Point",
              "latitude": 51.30345,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.21205
            },
            {
              "py/object": "Point",
              "latitude": 51.30251,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.2114
            },
            {
              "py/object": "Point",
              "latitude": 51.30296,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.21424
            }
          ],
          "subCodes": [
            "BA14 0LD",
            "BA14 0LE",
            "BA14 0LJ",
            "BA14 0LZ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JF9607",
      "engineerOnSiteTime": "2021-12-17T17:00:00.000+0000",
      "name": "BA14 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BA14 0LD",
        "BA14 0LE",
        "BA14 0LJ",
        "BA14 0LZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -2.21424,
              51.30296
            ],
            [
              -2.21332,
              51.30314
            ],
            [
              -2.21205,
              51.30345
            ],
            [
              -2.2114,
              51.30251
            ],
            [
              -2.21424,
              51.30296
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "14c0e012-3c14-441e-96f0-5a46905452a3",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.2128220757417214,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T17:49:00.000+0000",
      "latitude": 51.493671700024684,
      "estimatedRestoration": "2021-12-17T20:55:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JF9725'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JF9725",
      "reference": "JF9725",
      "name": "W4 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "W4 5DX",
        "W4 5EA",
        "W4 5JQ",
        "W4 5LY",
        "W4 5RA",
        "W4 5RE",
        "W4 5RF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.26727363268695215,
          51.493671700024684
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2021-12-17T19:00:00.000+0000",
      "UUID": "8b525fde-afcf-42ec-81a6-84b3f440c235",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.26727363268695215,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T17:55:00.000+0000",
      "latitude": 51.23367891582288,
      "estimatedRestoration": "2021-12-17T21:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JF9733'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JF9733",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.23278,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.73365
            },
            {
              "py/object": "Point",
              "latitude": 51.23338,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.73296
            },
            {
              "py/object": "Point",
              "latitude": 51.23474,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.73099
            },
            {
              "py/object": "Point",
              "latitude": 51.23288,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.72915
            },
            {
              "py/object": "Point",
              "latitude": 51.23278,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.73365
            }
          ],
          "subCodes": [
            "GU10 1DR",
            "GU10 1EG",
            "GU10 1EJ",
            "GU10 1ER",
            "GU10 1FF"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JF9733",
      "name": "GU10 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU10 1DR",
        "GU10 1EG",
        "GU10 1EJ",
        "GU10 1ER",
        "GU10 1FF"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.73365,
              51.23278
            ],
            [
              -0.73296,
              51.23338
            ],
            [
              -0.73099,
              51.23474
            ],
            [
              -0.72915,
              51.23288
            ],
            [
              -0.73365,
              51.23278
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2021-12-17T18:30:00.000+0000",
      "UUID": "9847315b-6d2e-476f-88c6-83e15ef22453",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7324289450888255,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T15:03:00.000+0000",
      "latitude": 58.34973420227302,
      "estimatedRestoration": "2021-12-17T19:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JF9617'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JF9617",
      "reference": "JF9617",
      "name": "KW2 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW2 6AA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.165650346439842,
          58.34973420227302
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2021-12-17T15:30:00.000+0000",
      "UUID": "c10fc882-4deb-469b-be54-b38af60bffd4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.165650346439842,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T15:21:00.000+0000",
      "latitude": 57.6941357731143,
      "estimatedRestoration": "2021-12-17T20:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JF9646'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JF9646",
      "reference": "JF9646",
      "name": "IV30 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "IV30 4JX",
        "IV30 5QA",
        "IV30 5QB",
        "IV30 5QD",
        "IV30 5QH",
        "IV30 5QJ",
        "IV30 5QL",
        "IV30 5QN",
        "IV30 5QP",
        "IV30 5QQ",
        "IV30 5QR",
        "IV30 5QS",
        "IV30 5QU",
        "IV30 5QW",
        "IV30 5QX",
        "IV30 5QY",
        "IV30 5QZ",
        "IV30 5RF",
        "IV30 5RH",
        "IV30 5RJ",
        "IV30 5RL",
        "IV30 5RN",
        "IV30 5RR",
        "IV30 5RW",
        "IV30 5SX",
        "IV30 5WA",
        "IV30 5WB",
        "IV30 5WD",
        "IV30 5WE",
        "IV30 5WF",
        "IV30 5WX",
        "IV30 5XU",
        "IV30 5XW",
        "IV30 5XY",
        "IV30 5YA",
        "IV30 5YB",
        "IV30 5YD",
        "IV30 5YE",
        "IV30 5YF",
        "IV30 5YG",
        "IV30 5YP",
        "IV30 5YQ",
        "IV30 8RS",
        "IV30 8UU",
        "IV30 8XN",
        "IV31 6SP"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.404210572218496,
          57.6941357731143
        ],
        "type": "Point"
      },
      "UUID": "5cddd2aa-70e0-420b-8e36-ff6ddf4e9ee9",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.404210572218496,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-17T13:30:00.000+0000",
      "latitude": 56.67296316537496,
      "estimatedRestoration": "2021-12-17T19:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JF9539'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JF9539",
      "reference": "JF9539",
      "name": "DD8 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD8 4EP",
        "DD8 4EQ",
        "DD8 4ER",
        "DD8 4ES"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.0057028489253637,
          56.67296316537496
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2021-12-17T14:40:00.000+0000",
      "UUID": "1758bde2-20a9-49d2-8f21-46e8705d2901",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.0057028489253637,
      "resolved": false
    }
  ]
}
