{
  "Faults": [
    {
      "latitude": 51.49977145401303,
      "type": "LV",
      "reference": "MV4346",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-15T11:25:00.000+0000",
      "affectedCustomerCount": 41,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "2e642f88-e8b6-412a-9ead-4014b4dfcd63",
      "minLongitude": -0.3832,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.3800832818159411,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T09:20:00.000+0000",
      "estimatedRestoration": "2023-11-16T11:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV4346'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV4346",
      "maxLongitude": -0.378,
      "minLatitude": 51.4987,
      "name": "UB2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "UB2 4EA",
        "UB2 4ED",
        "UB2 4EE",
        "UB2 4EG",
        "UB2 4EH",
        "UB2 4EQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3832,
              51.501
            ],
            [
              -0.378,
              51.501
            ],
            [
              -0.378,
              51.4987
            ],
            [
              -0.3832,
              51.4987
            ],
            [
              -0.3832,
              51.501
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-15T11:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.501,
      "etrUpdate": true
    },
    {
      "latitude": 50.87914846256376,
      "type": "LV",
      "reference": "MV4927",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-15T15:00:00.000+0000",
      "affectedCustomerCount": 210,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "954b7635-430f-4683-a18a-aa3a13f9ded6",
      "minLongitude": -1.8823,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.8794861503950961,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T14:10:00.000+0000",
      "estimatedRestoration": "2023-11-15T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV4927'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV4927",
      "maxLongitude": -1.8712,
      "minLatitude": 50.8695,
      "name": "BH31 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "BH31 6AE",
        "BH31 6DP",
        "BH31 6DR",
        "BH31 6DS",
        "BH31 6DT",
        "BH31 6DY",
        "BH31 6DZ",
        "BH31 6HD",
        "BH31 6HT",
        "BH31 6YE",
        "BH31 6YF",
        "BH31 6YR"
      ],
      "location": {
        "coordinates": [
          [
            [
              -1.8823,
              50.8819
            ],
            [
              -1.8712,
              50.8819
            ],
            [
              -1.8712,
              50.8695
            ],
            [
              -1.8823,
              50.8695
            ],
            [
              -1.8823,
              50.8819
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-15T15:15:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8819,
      "etrUpdate": true
    },
    {
      "latitude": 51.40051766707532,
      "type": "LV",
      "reference": "MV5072",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-15T17:15:00.000+0000",
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "0678d25c-da50-4b9f-82ae-3726fdbf6869",
      "minLongitude": -0.6378,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6321956560996774,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T15:36:00.000+0000",
      "estimatedRestoration": "2023-11-16T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5072'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5072",
      "maxLongitude": -0.6242,
      "minLatitude": 51.3983,
      "name": "SL5 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "SL5 0LR",
        "SL5 0LX",
        "SL5 0NB",
        "SL5 0NE",
        "SL5 0NF",
        "SL5 0NG",
        "SL5 0NQ",
        "SL5 0NS",
        "SL5 0NT",
        "SL5 0NX",
        "SL5 0NZ",
        "SL5 0PA",
        "SL5 0QH",
        "SL5 0QQ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6378,
              51.4043
            ],
            [
              -0.6242,
              51.4043
            ],
            [
              -0.6242,
              51.3983
            ],
            [
              -0.6378,
              51.3983
            ],
            [
              -0.6378,
              51.4043
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-15T17:45:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4043,
      "etrUpdate": true
    },
    {
      "latitude": 51.486363561997145,
      "type": "LV",
      "reference": "MV3253",
      "etaUpdate": true,
      "engineerOnSiteTime": "2023-11-14T13:50:00.000+0000",
      "affectedCustomerCount": 2,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "4a83b626-52c6-4d0a-82c2-ee155f22f033",
      "minLongitude": -0.3264,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.3237522858695663,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T14:00:00.000+0000",
      "estimatedRestoration": "2023-11-16T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV3253'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV3253",
      "maxLongitude": -0.3194,
      "minLatitude": 51.4855,
      "name": "TW8 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "TW8 9EX",
        "TW8 9EZ"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.3264,
              51.4889
            ],
            [
              -0.3194,
              51.4889
            ],
            [
              -0.3194,
              51.4855
            ],
            [
              -0.3264,
              51.4855
            ],
            [
              -0.3264,
              51.4889
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.4889,
      "etrUpdate": true
    },
    {
      "latitude": 51.375722457719725,
      "type": "LV",
      "reference": "MV5396",
      "etaUpdate": true,
      "affectedCustomerCount": 10,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "fdde1007-6337-4b15-8549-7f7e26f01102",
      "minLongitude": -0.6712,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.670147780291595,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-15T22:56:00.000+0000",
      "estimatedRestoration": "2023-11-16T08:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. We are working hard to get the power back on as quickly as we can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5396'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5396",
      "maxLongitude": -0.6689,
      "minLatitude": 51.3746,
      "name": "GU20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "GU20 6NE"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.6712,
              51.3768
            ],
            [
              -0.6689,
              51.3768
            ],
            [
              -0.6689,
              51.3746
            ],
            [
              -0.6712,
              51.3746
            ],
            [
              -0.6712,
              51.3768
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-16T00:20:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 51.3768,
      "etrUpdate": true
    },
    {
      "latitude": 50.712759503669325,
      "type": "LV",
      "reference": "MV5483",
      "etaUpdate": true,
      "affectedCustomerCount": 31,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "d050e53f-4907-435a-bf10-50a52efb6f91",
      "minLongitude": -2.3528,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.336062453509803,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T05:57:00.000+0000",
      "estimatedRestoration": "2023-11-16T09:05:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5483'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5483",
      "maxLongitude": -2.3257,
      "minLatitude": 50.6933,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 8GE",
        "DT2 8GF",
        "DT2 8TP",
        "DT2 8TT",
        "DT2 8TU",
        "DT2 8TW"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.3528,
              50.7525
            ],
            [
              -2.3257,
              50.7525
            ],
            [
              -2.3257,
              50.6933
            ],
            [
              -2.3528,
              50.6933
            ],
            [
              -2.3528,
              50.7525
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.7525,
      "etrUpdate": true
    },
    {
      "latitude": 50.80670786317226,
      "type": "LV",
      "reference": "MV5774",
      "etaUpdate": true,
      "affectedCustomerCount": 5,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "19142c30-687e-4dae-a694-519688cdfa9b",
      "minLongitude": -0.8716,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7797115896872497,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:37:00.000+0000",
      "estimatedRestoration": "2023-11-16T12:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5774'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5774",
      "maxLongitude": -0.6862,
      "minLatitude": 50.7691,
      "name": "PO20 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "PO20 3TT",
        "PO20 8PS"
      ],
      "location": {
        "coordinates": [
          [
            [
              -0.8716,
              50.8485
            ],
            [
              -0.6862,
              50.8485
            ],
            [
              -0.6862,
              50.7691
            ],
            [
              -0.8716,
              50.7691
            ],
            [
              -0.8716,
              50.8485
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-16T08:00:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8485,
      "etrUpdate": true
    },
    {
      "latitude": 50.79295530956629,
      "type": "LV",
      "reference": "MV5815",
      "etaUpdate": true,
      "affectedCustomerCount": 28,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "12c4f5a6-4b30-40f7-b202-fa4befdf390e",
      "minLongitude": -2.4879,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.4691232412043793,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T07:18:00.000+0000",
      "estimatedRestoration": "2023-11-16T10:20:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5815'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5815",
      "maxLongitude": -2.3879,
      "minLatitude": 50.7051,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 7GT",
        "DT2 7GU",
        "DT2 7JF",
        "DT2 7JR",
        "DT2 7JS",
        "DT2 7JU",
        "DT2 7JW",
        "DT2 7JX",
        "DT2 7JY",
        "DT2 7LF",
        "DT2 7RZ",
        "DT2 8AD"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4879,
              50.8137
            ],
            [
              -2.3879,
              50.8137
            ],
            [
              -2.3879,
              50.7051
            ],
            [
              -2.4879,
              50.7051
            ],
            [
              -2.4879,
              50.8137
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8137,
      "etrUpdate": true
    },
    {
      "latitude": 50.80976845717197,
      "type": "LV",
      "reference": "MV5808",
      "etaUpdate": true,
      "affectedCustomerCount": 22,
      "networkId": "com.sse.ssepd.sepd",
      "UUID": "600bb4ee-83ab-49e9-bfcc-488f78cf556a",
      "minLongitude": -2.4787,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.4721019103956157,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:04:00.000+0000",
      "estimatedRestoration": "2023-11-16T10:25:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5808'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5808",
      "maxLongitude": -2.4527,
      "minLatitude": 50.8052,
      "name": "DT2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DT2 7JN",
        "DT2 7JP",
        "DT2 7JQ",
        "DT2 7JW",
        "DT2 7TS"
      ],
      "location": {
        "coordinates": [
          [
            [
              -2.4787,
              50.8197
            ],
            [
              -2.4527,
              50.8197
            ],
            [
              -2.4527,
              50.8052
            ],
            [
              -2.4787,
              50.8052
            ],
            [
              -2.4787,
              50.8197
            ]
          ]
        ],
        "type": "Polygon"
      },
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 50.8197,
      "etrUpdate": true
    },
    {
      "latitude": 56.47204440523177,
      "type": "LV",
      "reference": "MV5772",
      "etaUpdate": true,
      "affectedCustomerCount": 13,
      "networkId": "com.sse.ssepd.shepd",
      "UUID": "d726da0e-a1ff-437d-88bc-38b07117ac26",
      "minLongitude": -3.0471,
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.043919487786967,
      "resolved": false,
      "py/object": "Fault",
      "srtUpdate": true,
      "loggedAt": "2023-11-16T06:34:00.000+0000",
      "estimatedRestoration": "2023-11-16T10:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. Our engineers are on site working hard to get the power back on as quickly as they can. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'MV5772'",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/MV5772",
      "maxLongitude": -3.0403,
      "minLatitude": 56.471,
      "name": "DD2 Area",
      "otherUpdate": true,
      "affectedAreas": [
        "DD2 4NY",
        "DD2 4PD",
        "DD2 4RX"
      ],
      "location": {
        "coordinates": [
          [
            [
              -3.0471,
              56.4728
            ],
            [
              -3.0403,
              56.4728
            ],
            [
              -3.0403,
              56.471
            ],
            [
              -3.0471,
              56.471
            ],
            [
              -3.0471,
              56.4728
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2023-11-16T07:30:00.000+0000",
      "region": "com.opengrid.geo.world.europe.gb",
      "maxLatitude": 56.4728,
      "etrUpdate": true
    }
  ]
}
