{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-17T08:00:00.000+0000",
      "latitude": 50.819114379997195,
      "estimatedRestoration": "2022-03-21T17:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206523'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206523",
      "reference": "206523",
      "name": "DT11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT11 9DH"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.1515012825925037,
          50.819114379997195
        ],
        "type": "Point"
      },
      "UUID": "f011c6a7-f0bb-453e-881f-bc5e70d1db92",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.1515012825925037,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-18T15:47:00.000+0000",
      "latitude": 51.03496363438736,
      "estimatedRestoration": "2022-03-18T23:59:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ2970'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ2970",
      "reference": "JQ2970",
      "name": "SO51 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "SO51 0NP",
        "SO51 0NQ",
        "SO51 0NS",
        "SO51 0NT"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.507655803316451,
          51.03496363438736
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-18T16:30:00.000+0000",
      "UUID": "655f98fc-5715-41ce-be0c-6c5abad5cb83",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.507655803316451,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-18T16:37:00.000+0000",
      "latitude": 50.787476504828795,
      "estimatedRestoration": "2022-03-19T02:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ3001'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ3001",
      "reference": "JQ3001",
      "engineerOnSiteTime": "2022-03-18T17:30:00.000+0000",
      "name": "PO11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO11 0AA",
        "PO11 0AB",
        "PO11 0AE",
        "PO11 0JB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.987889915762343,
          50.787476504828795
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-18T17:45:00.000+0000",
      "UUID": "2ad97877-4b89-40d4-a205-1afed21a0319",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.987889915762343,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-18T20:31:00.000+0000",
      "latitude": 51.59079934769097,
      "estimatedRestoration": "2022-03-18T23:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ3055'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ3055",
      "reference": "JQ3055",
      "name": "OX11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX11",
        "OX11 9LN",
        "OX11 9LP",
        "OX11 9LR",
        "OX11 9ND"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.242016009653747,
          51.59079934769097
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-18T21:10:00.000+0000",
      "UUID": "3ab080ef-6001-4bd8-b34e-75794eb40acb",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.242016009653747,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-18T21:14:00.000+0000",
      "latitude": 51.58639462690128,
      "estimatedRestoration": "2022-03-19T00:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JQ3060'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JQ3060",
      "reference": "JQ3060",
      "name": "OX11 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "OX11 0PD",
        "OX11 0PE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -1.3061750219576702,
          51.58639462690128
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-03-18T22:30:00.000+0000",
      "UUID": "424e1c62-2689-4c25-9ae5-d1ddedd32ab5",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3061750219576702,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-03-14T10:00:00.000+0000",
      "latitude": 59.11693007695559,
      "estimatedRestoration": "2022-03-21T19:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '206022'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/206022",
      "reference": "206022",
      "name": "KW17 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "KW17 2PJ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.119189129637787,
          59.11693007695559
        ],
        "type": "Point"
      },
      "UUID": "12c3f463-535e-47d1-a23a-cd851a71c99f",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.119189129637787,
      "resolved": false
    }
  ]
}
