{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-31T10:05:00.000+0000",
      "latitude": 51.3353668243519,
      "estimatedRestoration": "2021-12-31T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG6380'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG6380",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.33478,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.84811
            },
            {
              "py/object": "Point",
              "latitude": 51.3353668243519,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.8476553275821476
            },
            {
              "py/object": "Point",
              "latitude": 51.33595,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.84721
            }
          ],
          "subCodes": [
            "GU46 6FA",
            "GU46 6FQ"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG6380",
      "engineerOnSiteTime": "2021-12-31T12:30:00.000+0000",
      "name": "GU46 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU46 6FA",
        "GU46 6FQ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.84811,
              51.33478
            ],
            [
              -0.8476553275821476,
              51.3353668243519
            ],
            [
              -0.84721,
              51.33595
            ],
            [
              -0.84811,
              51.33478
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "c7e37c62-66ec-43a6-b50d-b8ce6410bec8",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.8476553275821476,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-31T13:28:00.000+0000",
      "latitude": 51.373193385274526,
      "estimatedRestoration": "2021-12-31T17:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG6493'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG6493",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.37205,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.45939
            },
            {
              "py/object": "Point",
              "latitude": 51.373193385274526,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.4578504408288564
            },
            {
              "py/object": "Point",
              "latitude": 51.37452,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.45638
            },
            {
              "py/object": "Point",
              "latitude": 51.37205,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.45939
            }
          ],
          "subCodes": [
            "RG17 9QP",
            "RG17 9QR"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG6493",
      "name": "RG17 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG17 9QP",
        "RG17 9QR"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.45939,
              51.37205
            ],
            [
              -1.4578504408288564,
              51.373193385274526
            ],
            [
              -1.45638,
              51.37452
            ],
            [
              -1.45939,
              51.37205
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2021-12-31T14:00:00.000+0000",
      "UUID": "e6ca86d2-430f-4023-bd90-ce0daeb62f5e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.4578504408288564,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2021-12-31T13:47:00.000+0000",
      "latitude": 50.69350900276008,
      "estimatedRestoration": "2021-12-31T17:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG6497'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG6497",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.69215,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.3063
            },
            {
              "py/object": "Point",
              "latitude": 50.69337,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.30455
            },
            {
              "py/object": "Point",
              "latitude": 50.69486,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.3034
            },
            {
              "py/object": "Point",
              "latitude": 50.6938,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.30465
            },
            {
              "py/object": "Point",
              "latitude": 50.69215,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -1.3063
            }
          ],
          "subCodes": [
            "PO30 1DP",
            "PO30 1DR",
            "PO30 1DS",
            "PO30 1DT"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JG6497",
      "engineerOnSiteTime": "2021-12-31T14:20:00.000+0000",
      "name": "PO30 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "PO30 1DP",
        "PO30 1DR",
        "PO30 1DS",
        "PO30 1DT"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -1.3063,
              50.69215
            ],
            [
              -1.30455,
              50.69337
            ],
            [
              -1.3034,
              50.69486
            ],
            [
              -1.30465,
              50.6938
            ],
            [
              -1.3063,
              50.69215
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "5d1e7964-616d-4f9b-a771-d6d0d293eea5",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -1.3046456580326573,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "Messages": [
        {
          "py/object": "Message",
          "senderName": "tobias.sell@sse.com",
          "senderUserId": "44833855-d575-41a0-92f7-7cd8a3b8dabd",
          "text": "we aim to restore power by 01:30.",
          "UUID": "6f105164-b94e-46d3-88e9-245467df6fdf",
          "py/class": "http://opengrid.com/givr/1.0#//Message",
          "sentDateTime": "2021-12-31T10:42:05.086+0000"
        }
      ],
      "loggedAt": "2021-12-31T10:27:00.000+0000",
      "latitude": 56.67856678146914,
      "estimatedRestoration": "2021-12-31T16:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JG6402'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JG6402",
      "reference": "JG6402",
      "engineerOnSiteTime": "2021-12-31T11:28:00.000+0000",
      "name": "DD8 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "DD8 4GP",
        "DD8 4GQ",
        "DD8 4GX",
        "DD8 4HN",
        "DD8 4HP",
        "DD8 4HQ",
        "DD8 4HU",
        "DD8 4HW",
        "DD8 4HX",
        "DD8 4QG"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.0049055606335613,
          56.67856678146914
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2021-12-31T11:30:00.000+0000",
      "UUID": "7f45270d-412b-4924-ab2b-2bb96717c278",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.0049055606335613,
      "resolved": false
    }
  ]
}
