{
  "Faults": [
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-16T08:00:00.000+0000",
      "latitude": 51.45764173118078,
      "estimatedRestoration": "2022-01-16T16:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '204985'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/204985",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.45695,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.94139
            }
          ],
          "name": "RG6 1AZ",
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "204985",
      "name": "RG6 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG6 1AZ"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -0.9412599502881887,
          51.45764173118078
        ],
        "type": "Point"
      },
      "UUID": "7b3c75ce-cd8a-431a-8eb6-3b57a076692d",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9412599502881887,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-16T09:44:00.000+0000",
      "latitude": 51.54263732009538,
      "estimatedRestoration": "2022-01-16T18:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ3880'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ3880",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.54377,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.91268
            },
            {
              "py/object": "Point",
              "latitude": 51.54263732009538,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.9084442477517606
            },
            {
              "py/object": "Point",
              "latitude": 51.54133,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.90422
            }
          ],
          "subCodes": [
            "RG9 2JE",
            "RG9 2LE"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JJ3880",
      "name": "RG9 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "RG9 2JE",
        "RG9 2LE"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.91268,
              51.54377
            ],
            [
              -0.9084442477517606,
              51.54263732009538
            ],
            [
              -0.90422,
              51.54133
            ],
            [
              -0.91268,
              51.54377
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-01-16T10:20:00.000+0000",
      "UUID": "9d2f4088-50b8-40fb-8b35-49b41457f0e4",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.9084442477517606,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-16T11:21:00.000+0000",
      "latitude": 50.67768729798376,
      "estimatedRestoration": "2022-01-16T14:30:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ3903'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ3903",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.68021,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -2.25607
            }
          ],
          "name": "DT2 8GB",
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JJ3903",
      "name": "DT2 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "DT2 8FT",
        "DT2 8GB"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -2.2462941447803497,
          50.67768729798376
        ],
        "type": "Point"
      },
      "estimatedArrivalOnSiteTime": "2022-01-16T12:15:00.000+0000",
      "UUID": "82c2bca0-2ac0-4d0c-b4fd-90746e287e18",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -2.2462941447803497,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-16T12:00:00.000+0000",
      "latitude": 50.85920727028087,
      "estimatedRestoration": "2022-01-16T13:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '205200'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/205200",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 50.86007,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.65606
            },
            {
              "py/object": "Point",
              "latitude": 50.85649,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.65302
            },
            {
              "py/object": "Point",
              "latitude": 50.86226,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.64999
            },
            {
              "py/object": "Point",
              "latitude": 50.86007,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.65606
            }
          ],
          "subCodes": [
            "BN18 0SL",
            "BN18 0SN",
            "BN18 0SP",
            "BN18 0TA"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "205200",
      "name": "BN18 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "BN18 0SL",
        "BN18 0SN",
        "BN18 0SP",
        "BN18 0TA"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.65606,
              50.86007
            ],
            [
              -0.65302,
              50.85649
            ],
            [
              -0.64999,
              50.86226
            ],
            [
              -0.65606,
              50.86007
            ]
          ]
        ],
        "type": "Polygon"
      },
      "UUID": "741b21bd-4cda-4db4-89c7-945fec31c35e",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.6528806432418788,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-16T11:55:00.000+0000",
      "latitude": 51.22343726704842,
      "estimatedRestoration": "2022-01-16T15:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ3908'",
      "type": "LV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ3908",
      "Areas": [
        {
          "py/object": "Area",
          "Points": [
            {
              "py/object": "Point",
              "latitude": 51.22627,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75716
            },
            {
              "py/object": "Point",
              "latitude": 51.22544,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75706
            },
            {
              "py/object": "Point",
              "latitude": 51.22321,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75677
            },
            {
              "py/object": "Point",
              "latitude": 51.22168,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75497
            },
            {
              "py/object": "Point",
              "latitude": 51.22079,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75357
            },
            {
              "py/object": "Point",
              "latitude": 51.22287,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.753
            },
            {
              "py/object": "Point",
              "latitude": 51.22437,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75313
            },
            {
              "py/object": "Point",
              "latitude": 51.22627,
              "py/class": "http://opengrid.com/givr/1.0#//Point",
              "longitude": -0.75716
            }
          ],
          "subCodes": [
            "GU10 1FD",
            "GU10 1FG",
            "GU10 1PH",
            "GU10 1PJ",
            "GU10 1PL",
            "GU10 1PN",
            "GU10 1PP",
            "GU10 1QG"
          ],
          "py/class": "http://opengrid.com/givr/1.0#//Area"
        }
      ],
      "reference": "JJ3908",
      "name": "GU10 Area",
      "networkId": "com.sse.ssepd.sepd",
      "affectedAreas": [
        "GU10 1FD",
        "GU10 1FG",
        "GU10 1PH",
        "GU10 1PJ",
        "GU10 1PL",
        "GU10 1PN",
        "GU10 1PP",
        "GU10 1QG"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          [
            [
              -0.75716,
              51.22627
            ],
            [
              -0.75706,
              51.22544
            ],
            [
              -0.75677,
              51.22321
            ],
            [
              -0.75497,
              51.22168
            ],
            [
              -0.75357,
              51.22079
            ],
            [
              -0.753,
              51.22287
            ],
            [
              -0.75313,
              51.22437
            ],
            [
              -0.75716,
              51.22627
            ]
          ]
        ],
        "type": "Polygon"
      },
      "estimatedArrivalOnSiteTime": "2022-01-16T12:30:00.000+0000",
      "UUID": "7d3ca0a2-f729-4ae7-92ba-7be748ebb9a1",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -0.7551073463587068,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-16T10:00:00.000+0000",
      "latitude": 56.575818861376774,
      "estimatedRestoration": "2022-01-16T15:00:00.000+0000",
      "message": "We're sorry for the loss of supply. The reason you're currently without power is a planned outage in the areas listed. We have turned off your electricity supply to allow us to safely carry out essential work to our electrical equipment. By doing this, it'll help us to improve the reliability of our service to you for the future. If you have any questions or require more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) with reference  '204762'. You will have received a letter from us confirming your power will be interrupted with specific information relating to your property. If you did not receive this letter, you can assume your power will not be interrupted.",
      "type": "PSI",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/204762",
      "reference": "204762",
      "name": "PH8 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "PH8 0EP",
        "PH8 0ER",
        "PH8 0HU"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -3.5906252086707084,
          56.575818861376774
        ],
        "type": "Point"
      },
      "UUID": "4df5600f-770b-4743-b585-3307578d1375",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -3.5906252086707084,
      "resolved": false
    },
    {
      "py/object": "Fault",
      "loggedAt": "2022-01-16T12:09:00.000+0000",
      "latitude": 57.13964448345776,
      "estimatedRestoration": "2022-01-16T14:00:00.000+0000",
      "message": "We’re sorry for the loss of supply. We currently have a fault affecting the areas listed. If you need more information, please call us on 105 or send us a message on <a href=\"http://m.me/ssencommunity/\">Facebook</a> or Twitter (<a href=\"https://twitter.com/ssencommunity\">@ssencommunity</a>) and quote reference 'JJ3916'",
      "type": "HV",
      "uri": "http://api.sse.com/powerdistribution/network/v3/api/fault/JJ3916",
      "reference": "JJ3916",
      "name": "HS8 Area",
      "networkId": "com.sse.ssepd.shepd",
      "affectedAreas": [
        "HS8 5TB",
        "HS8 5TE",
        "HS8 5UB",
        "HS8 5UD"
      ],
      "location": {
        "__json": true,
        "coordinates": [
          -7.348052949534131,
          57.13964448345776
        ],
        "type": "Point"
      },
      "UUID": "15bb1220-5784-4ba3-a7f8-bdaf09b89d01",
      "region": "com.opengrid.geo.world.europe.gb",
      "py/class": "http://opengrid.com/givr/1.0#//Fault",
      "longitude": -7.348052949534131,
      "resolved": false
    }
  ]
}
